config/routes.rb
TheBookDemo::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  resources :ratings

  resources :books

  resources :users, :only => [:show] do
    member do
      put 'add_book'
      put 'rate_book'
      get 'admin_change_user_rating'
      put 'admin_update_user_rating'
    end
  end

  root :to => 'books#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)      not null
#  email                  :string(255)      default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  admin                  :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :name

  validates :name, :email, :presence => true
  validates_uniqueness_of :email
  validates :email, :length => { :minimum => 3, :maximum => 254 },
    :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i },
    :allow_blank =>  true

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40},
                       :on => :create

  has_many :ratings
  has_many :books, :through => :ratings, :source => :book

  def read? book
    if books.include? book
      true
    else
      false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :validate_self, :only => [:show, :edit, :update]
  before_filter :authenticate_admin, :only => [:admin_change_user_rating,
                                               :admin_change_user_rating]

  def validate_self
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @can_edit = true
    end
  end

  def authenticate_admin
    if !current_user.admin?
      redirect_to root_url,
        :notice => "You are not authorized to access this page." and return
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user_books = @user.books.page params[:page]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    if !@can_edit
      redirect_to user_path(@user), :notice => "You are not allowed to edit the " +
      "information of other users." and return
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    if !@can_edit
      redirect_to user_path(@user), :notice => "You are not allowed to edit the " +
      "information of other users." and return
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1/add_book
  def add_book
    @user = User.find(params[:id])
    @book = Book.find(params[:book_id])
    rating = Rating.new(user_id: @user.id, book_id: @book.id)
    if rating.save!
      render :json => true
    else
      render :json => false
    end
  end

  # PUT /users/1/rate_book
  def rate_book
    rated = Rating.rate(params[:id], params[:book_id], params[:rating])
    if rated
      render :json => true
    else
      render :json => false
    end
  end

  def admin_change_user_rating
    @user = User.find(params[:user_id])
    @book = Book.find(params[:book_id])
    @current_rating = @book.get_rating @user.id
  end

  def admin_update_user_rating
    rated = Rating.rate(params[:user_id], params[:book_id], params[:rating])
    @user = User.find(params[:user_id])
    respond_to do |format|
      if rated
        format.html { redirect_to @user, notice: 'Rating was successfully updated.' }
        format.json { render json: true }
      else
        format.html { redirect_to @user, error: 'Could not update the Rating.' }
        format.json { render json: false }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/admin_change_user_rating.html.haml
%br

%legend Changing #{@user.name}'s rating for #{@book.title}

%br

%b Current Rating - #{@current_rating}

.clear

%b Change Rating -
=form_tag admin_update_user_rating_user_path, :method => "put", :class => "form-search" do
  = select_tag "rating",
    "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>".html_safe
  = hidden_field_tag :user_id, @user.id
  = hidden_field_tag :book_id, @book.id
  = submit_tag "Change", :name => nil,
    :class => 'btn'

= link_to 'Back', :back, :class => 'btn'

app/views/users/edit.html.haml
%legend Editing Profile

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', :back

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', :back

app/views/users/show.html.haml
%p
  %b.lead Name: #{@user.name}
%p
  %b.lead Email: #{@user.email}

.clear

%p.lead #{@user.name}'s Books
- if @user_books.blank?
  %p You haven't added any books yet.
- else
  = render :partial => 'books/index_partial', :locals => { :books => @user_books, :show_user => @user }

%br

- if @can_edit
  = link_to 'Add a new Book', new_book_path, :class => 'btn'
= link_to 'Back', :back, :class => 'btn'