config/routes.rb
TheBookDemo::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  resources :ratings

  resources :books

  resources :users, :only => [:show] do
    member do
      put 'add_book'
      put 'rate_book'
      get 'admin_change_user_rating'
      put 'admin_update_user_rating'
    end
  end

  root :to => 'books#index'

end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :integer          not null, primary key
#  book_id    :integer          not null
#  user_id    :integer          not null
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Rating < ActiveRecord::Base
  attr_accessible :book_id, :rating, :user_id

  validates :book_id, :user_id, :presence => true
  validates :book_id, :uniqueness => {:scope => :user_id,
    :message => "User has already rated this book."}
  validates_inclusion_of :rating, :in => [1,2,3,4,5], :allow_blank => true,
    :message => "Rating can only be in the range of 1 to 5"

  belongs_to :book
  belongs_to :user

  def self.rate(user_id, book_id, user_rating)
    user =  User.find(user_id)
    book = Book.find(book_id)
    rating = Rating.where(user_id: user.id, book_id: book.id).first
    if !rating
      rating = Rating.new(user_id: user.id, book_id: book.id)
    end
    rating.rating = user_rating
    if rating.save!
      true
    else
      false
    end
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_filter :authenticate_user!

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.haml
= form_for @rating do |f|
  - if @rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rating.errors.count, "error")} prohibited this rating from being saved:"
      %ul
        - @rating.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :book_id
    = f.number_field :book_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :rating
    = f.number_field :rating
  .actions
    = f.submit 'Save'

app/views/ratings/edit.html.haml
%h1 Editing rating

= render 'form'

= link_to 'Show', @rating
\|
= link_to 'Back', :back

app/views/ratings/index.html.haml
%h1 Listing ratings

%table
  %tr
    %th Book
    %th User
    %th Rating
    %th
    %th
    %th

  - @ratings.each do |rating|
    %tr
      %td= rating.book_id
      %td= rating.user_id
      %td= rating.rating
      %td= link_to 'Show', rating
      %td= link_to 'Edit', edit_rating_path(rating)
      %td= link_to 'Destroy', rating, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Rating', new_rating_path

app/views/ratings/new.html.haml
%h1 New rating

= render 'form'

= link_to 'Back', :back

app/views/ratings/show.html.haml
%p#notice= notice

%p
  %b Book:
  = @rating.book_id
%p
  %b User:
  = @rating.user_id
%p
  %b Rating:
  = @rating.rating

= link_to 'Edit', edit_rating_path(@rating)
\|
= link_to 'Back', :back