config/routes.rb
TheBookDemo::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  resources :ratings

  resources :books

  resources :users, :only => [:show] do
    member do
      put 'add_book'
      put 'rate_book'
      get 'admin_change_user_rating'
      put 'admin_update_user_rating'
    end
  end

  root :to => 'books#index'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  author     :string(255)      not null
#  isbn       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  paginates_per 10
  attr_accessible :author, :isbn, :title

  validates :title, :author, :isbn, :presence => true
  validates_uniqueness_of :isbn

  has_many :ratings
  has_many :users, :through => :ratings, :source => :user

  def self.search(search_term, page)
    if !search_term
      return Book.order(:title).page(page)
    end
    Book.where('(lower(title) like ?) or (lower(author) like ?) or (lower(isbn) like ?)',
      "%#{search_term}%", "%#{search_term}%", "%#{search_term}%").order(:title).page(page)
  end

  def self.create_new(params, current_user=nil)
    book = Book.new(params[:book])
    Book.transaction do
      begin
        book.save!
        if current_user
          rating = Rating.new(user_id: current_user.id, book_id: book.id)
          rating.save!
        end
      rescue ActiveRecord::RecordInvalid
        raise ActiveRecord::Rollback
      end
    end
    book
  end

  def get_rating user_id
    user = User.find(user_id)
    rating = ratings.where(:user_id => user_id).first
    if rating and rating.rating
      rating.rating
    else
      "Not Rated"
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:index]
  before_filter :validate_owner, :only => [:show, :edit, :update, :destroy]

  def validate_owner
    @book = Book.find(params[:id])
    if @book.users.include? current_user
      @can_edit = true
      @current_user_rating = @book.ratings.where(:user_id => current_user.id).first
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.search params[:search], params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    if !@can_edit
      redirect_to books_path, :notice => "You are not allowed to edit the " +
      "books that have been added by others." and return
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.create_new(params, current_user)

    respond_to do |format|
      if @book.id
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    if !@can_edit
      redirect_to books_path, :notice => "You are not allowed to edit the " +
      "books that have been added by others." and return
    end

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if !@can_edit
      redirect_to books_path, :notice => "You are not allowed to edit the " +
      "books that have been added by others." and return
    end
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title, :required => true
  .field
    = f.label :author
    = f.text_field :author, :required => true
  .field
    = f.label :isbn
    = f.text_field :isbn, :required => true
  .actions
    = f.submit 'Save', :class => 'btn'

app/views/books/_index_partial.html.haml
- if !defined? books
  - @books = @books
- else
  - @books = books

%p
  .paginate
    =paginate @books

%table.table.table-bordered
  %tr
    %th Title
    %th Author
    %th Isbn
    - if defined? show_user
      %th Rating

  - @books.each do |book|
    %tr
      %td= link_to book.title, book
      %td= book.author
      %td= book.isbn
      - if defined? show_user
        %td= book.get_rating show_user.id
      - if user_signed_in?
        - if !current_user.read? book
          %td= link_to "Add this Book to your list", "#",
            :class => 'add-book-link', :book_id => book.id, :user_id => current_user.id
        - else
          %td= "You have read this Book"
        - if current_user.admin? and defined? show_user
          %td= link_to "Change #{show_user.name}'s rating for this Book",
            admin_change_user_rating_user_path(current_user, :user_id => show_user.id, :book_id => book.id)

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', :back

app/views/books/index.html.haml
%h1 Listing books

%legend Search Book by it's Title, Author or ISBN

=form_tag books_path, :class => "form-search", :method => "get" do
  .search
    = text_field_tag 'search', '', value: params[:search]
    = submit_tag "Search", :name => nil,
      :class => 'btn'

= render :partial => 'index_partial'

%br

- if user_signed_in?
  = link_to 'Add a new Book', new_book_path, :class => 'btn'

app/views/books/new.html.haml
%legend New Book

= render 'form'

app/views/books/show.html.haml
%p#notice= notice

%p
  %b.lead Title: #{@book.title}
%p
  %b.lead Author: #{@book.author}
%p
  %b.lead Isbn: #{@book.isbn}

.clear

- if @can_edit
  - if @current_user_rating and @current_user_rating.rating
    %b.current-rating Your rating - #{@current_user_rating.rating}
    %br
    %b.rating-label Change your rating -
  - else
    %b.current-rating Your rating - You haven't rated this book yet
    %br
    %b.rating-label Rate this Book -
  = select_tag "rating",
    "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>".html_safe,
    :class => 'select-rating', :book_id => @book.id, :user_id => current_user.id

.clear


%p.lead Users who have read this book -
- if @book.ratings.blank?
  %p.lead No one has read this book yet.
- else
  %table.table.table-bordered
    %tr
      %th Name
      %th Rating

    - @book.ratings.each do |rating|
      %tr
        %td= link_to rating.user.name, rating.user
        %td= rating.rating ? rating.rating : "Not Rated"


%br

- if @can_edit
  = link_to 'Edit', edit_book_path(@book), :class => 'btn'
= link_to 'Back', :back, :class => 'btn'